DROP SEQUENCE IDEIA_SEQ;

DROP SEQUENCE ALUNO_SEQ;

DROP SEQUENCE DEPARTAMENTOSOPET_SEQ;

DROP SEQUENCE CURSO_SEQ;






DROP TABLE IDEIA;

DROP TABLE ALUNO;

DROP TABLE DEPARTAMENTOSOPET;

DROP TABLE CURSO;

  
  CREATE SEQUENCE DEPARTAMENTOSOPET_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  
   CREATE SEQUENCE CURSO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE ALUNO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

  
CREATE SEQUENCE IDEIA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
 
  CREATE TABLE DEPARTAMENTOSOPET
 (
 ID              INT          NOT NULL PRIMARY KEY,
 EMAIL           VARCHAR(200) NOT NULL,
 SENHA           VARCHAR(15)  NOT NULL,
 NOME            VARCHAR(200) NOT NULL
 );
 
 
 CREATE TABLE CURSO
 (
 ID               INT          NOT NULL PRIMARY KEY,
 EMAIL            VARCHAR(100) NULL,
 SENHA            VARCHAR(15)  NOT NULL,
 NOME             VARCHAR(200) NOT NULL,
 NOMECOORDENADOR  VARCHAR(200) NOT NULL
 );


 CREATE TABLE ALUNO
 (
 ID            INT           NOT NULL PRIMARY KEY,
 EMAIL         VARCHAR (200) NOT NULL,
 SENHA         VARCHAR  (15) NOT NULL,
 NOME          VARCHAR (200) NOT NULL,
 TELEFONE      DECIMAL (11)  NOT NULL,
 TURNO         VARCHAR (50)  NOT NULL,
 TURMA         VARCHAR (100) NOT NULL,
 ID_CURSO      INT           NOT NULL,
 CONSTRAINT    ALUNO_CURSO_FK
                FOREIGN KEY (ID_CURSO)
                REFERENCES CURSO(ID)
 );  

  

 CREATE TABLE IDEIA
 (
 ID                   INT            NOT NULL PRIMARY KEY,
 NOME                 VARCHAR(100)   NOT NULL,
 DESCRICAODOPROBLEMA  VARCHAR(500)   NOT NULL,
 RECOMENDACAO         VARCHAR(500)   NOT NULL,
 DATACADASTRO         DATE           NOT NULL,
 DATAANALISE          DATE               NULL,
 APROVADO             CHAR(1)            NULL,
 RESPOSTA             VARCHAR(500)       NULL,
 ID_ALUNO             INT            NOT NULL,
 ID_DEPARTAMENTOSOPET INT            NOT NULL,
 CONSTRAINT ALUNO_IDALUNO_FK 
            FOREIGN KEY(ID_ALUNO)
            REFERENCES ALUNO(ID),
 CONSTRAINT IDEIA_DEPARTAMENTOSOPET_FK
            FOREIGN KEY(ID_DEPARTAMENTOSOPET)
            REFERENCES DEPARTAMENTOSOPET(ID)
 );
















